build:
  buildStats:
    enable: true
    disableIDs: true
  cacheBusters:
  - source: assets/watching/hugo_stats\.json
    target: styles\.css
  - source: assets/.*\.(js|ts|jsx|tsx)
    target: (js|scripts|javascript)
  - source: assets/.*\.(css|sass|scss)$
    target: (css|styles|scss|sass)
  - source: (postcss|tailwind)\.config\.js
    target: (css|styles|scss|sass)
  - source: assets/.*\.(.*)$
    target: $1

module:
  mounts:
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
