# Hugo config
title = "Hextra Theme"

baseURL = "https://example.org"

disableKinds = ["taxonomy", "term"]

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
    title = 'Hextra Theme'
  [languages.ja]
    languageName = '日本語'
    weight = 2
    title = 'Hextra テーマ'

[module]
  [module.hugoVersion]
    extended = true
    min      = "0.115.1"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false


[menu]
  [[menu.main]]
    name = 'Documentation'
    pageRef = '/docs'
    weight = 10
  [[menu.main]]
    name = 'Showcase'
    pageRef = '/showcase'
    weight = 20
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
  [[menu.main]]
    name = 'Search'
    weight = 35
    params = { placeholder = 'Search documentation...' }
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com'
    weight = 40
    params = { icon = 'github' }
