version: "3"

tasks:
  dev:
    cmds:
      - hugo server --logLevel debug --enableGitInfo --source=exampleSite --themesDir=../.. --environment=theme --disableFastRender --buildDrafts --port 1313

  build:
    deps: [css]
    cmds:
      - hugo --minify --source=exampleSite --themesDir=../..

  css:
    cmds:
      - npx postcss --config postcss.config.js --env production assets/css/styles.css -o assets/css/compiled/main.css

  clean:
    cmds:
      - rm -rf public resources
