# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "Hextra"
license = "MIT"
licenselink = "https://github.com/imfing/hextra/blob/main/LICENSE"
description = "Modern, versatile theme for building beautiful websites with Hugo"
homepage = "https://github.com/imfing/hextra/"
demosite = ""
tags = ["Modern", "Elegant", "Blog", "Documentation"]
features = ["Responsive", "Dark Mode", "Search", "Syntax Highlighting", "Multilingual"]
min_version = "0.111.0"

[author]
  name = "Xin"
  homepage = "https://imfing.com"
